name: Build APK
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.22.0' # Fixed to a very stable version

      - name: Install dependencies
        run: flutter pub get
        working-directory: mobile_app

      - name: Clean build
        run: |
          cd mobile_app
          flutter clean
          rm -rf android/.gradle
          
      - name: Build APK
        run: flutter build apk --release
        working-directory: mobile_app

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk-alfareed
          path: mobile_app/build/app/outputs/flutter-apk/app-release.apk
